"""Regenerate the ticket board and mirror tickets to GitHub issues.

    python scripts/sync_tickets.py               # regenerate docs/tickets/INDEX.md only
    python scripts/sync_tickets.py --github      # also create issues for tickets that lack one
    python scripts/sync_tickets.py --github --dry-run

Tickets are the source of truth; GitHub issues are a mirror for people who prefer the web UI. A
ticket already carrying a `github:` field is never re-created, so the command is safe to re-run.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TICKETS = ROOT / "docs" / "tickets"
SKIP = {"INDEX.md", "TEMPLATE.md"}

PRIORITY_ORDER = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
STATUS_SECTIONS = [
    ("open", "Open"),
    ("in-progress", "In progress"),
    ("blocked", "Blocked"),
    ("review", "In review"),
    ("done", "Done"),
    ("wontfix", "Won't fix"),
]

#: Rubric labels naming the same row, so points are not double counted on the board.
ROW_ALIASES = {"A1": "A", "A2": "A", "B5": "B", "C3": "C", "J2": "J", "J3": "J"}

LABELS = [
    ("P0", "b60205", "Blocks a rubric row worth 3+ points, or blocks someone else"),
    ("P1", "d93f0b", "Smaller rubric row, or degraded evidence quality"),
    ("P2", "fbca04", "Quality, refactors, developer experience"),
    ("P3", "c2e0c6", "Optional"),
    ("feature", "1d76db", "New capability"),
    ("task", "0e8a16", "Defined work, no new capability"),
    ("chore", "ededed", "Housekeeping"),
    ("bug", "d73a4a", "Defect"),
    ("spike", "5319e7", "Time-boxed investigation"),
    ("gridworld", "c5def5", "Part I"),
    ("arena", "bfd4f2", "Part II"),
    ("training", "d4c5f9", "Training pipeline"),
    ("eval", "f9d0c4", "Evaluation and playback"),
    ("report", "fef2c0", "Report"),
    ("video", "fad8c7", "Video demonstration"),
    ("infra", "e4e669", "Tooling and repo"),
    ("part1", "006b75", "Part I — tabular Q-learning and SARSA in the gridworld"),
    ("part2", "8250df", "Part II — deep RL in the real-time arena"),
]

#: Which assignment part a ticket belongs to. `both` earns both labels, `none` earns neither —
#: submission packaging and the team table serve the whole project, not one half of it.
PART_LABELS = {"1": ["part1"], "2": ["part2"], "both": ["part1", "part2"], "none": []}
PART_DISPLAY = {"1": "I", "2": "II", "both": "I+II", "none": "—"}


def part_of(t: dict) -> str:
    """Normalise the `part:` frontmatter field, which YAML may hand back as an int."""
    return str(t.get("part", "none"))


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


def load_tickets() -> list[dict]:
    tickets = []
    for path in sorted(TICKETS.glob("A3-*.md")):
        if path.name in SKIP:
            continue
        text = path.read_text(encoding="utf-8")
        match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
        if not match:
            raise ValueError(f"{path.name}: missing or malformed frontmatter")
        meta = yaml.safe_load(match.group(1))
        meta["_path"] = path
        meta["_body"] = match.group(2).strip()
        if str(meta.get("part", "none")) not in PART_LABELS:
            raise ValueError(
                f"{path.name}: part must be one of {sorted(PART_LABELS)}, got {meta.get('part')!r}"
            )
        tickets.append(meta)
    return tickets


def sort_key(t: dict) -> tuple:
    return (PRIORITY_ORDER.get(t.get("priority", "P3"), 9), t["id"])


def write_index(tickets: list[dict]) -> None:
    by_status: dict[str, list[dict]] = {}
    for t in tickets:
        by_status.setdefault(t.get("status", "open"), []).append(t)

    # Two tickets can share a rubric row (G is split across the arena entities and renderer), so
    # count each row's points once.
    row_points: dict[str, float] = {}
    for t in tickets:
        row = str(t.get("rubric", "none"))
        if row == "none":
            continue
        row_points.setdefault(ROW_ALIASES.get(row, row), float(t.get("points_at_risk", 0)))
    tracked = sum(row_points.values())

    done = len(by_status.get("done", []))
    counts = " · ".join(
        f"**{len(by_status.get(key, []))} {label.lower()}**" for key, label in STATUS_SECTIONS
        if by_status.get(key)
    )

    lines = [
        "# Ticket board",
        "",
        "Generated by `scripts/sync_tickets.py`. Do not edit by hand — ask the `ticket-bot` agent to",
        "raise, update or close a ticket, or edit the ticket file and re-run the script.",
        "",
        f"{counts} · **{tracked:g} of 40 rubric points** tracked "
        f"(each row counted once, even where two tickets share it)",
        "",
    ]

    for key, label in STATUS_SECTIONS:
        rows = sorted(by_status.get(key, []), key=sort_key)
        lines += [f"## {label}", ""]
        if not rows:
            lines += ["_none_", ""]
            continue
        lines += [
            "| ID | Pri | Type | Part | Title | Rubric | Pts | Area | Owner | Issue |",
            "|----|-----|------|------|-------|--------|-----|------|-------|-------|",
        ]
        for t in rows:
            pts = t.get("points_at_risk", 0)
            pts_s = f"{float(pts):g}" if pts else "—"
            issue = t.get("github", "")
            issue_s = f"[#{issue.rsplit('/', 1)[-1]}]({issue})" if issue else "—"
            blocked = ", ".join(t.get("blocked_by") or [])
            title = t["title"] + (f" _(blocked by {blocked})_" if blocked and key == "open" else "")
            lines.append(
                f"| [{t['id']}]({t['_path'].name}) | {t.get('priority', '')} | {t.get('type', '')} "
                f"| {PART_DISPLAY.get(part_of(t), '—')} "
                f"| {title} | {t.get('rubric', 'none')} | {pts_s} | {t.get('area', '')} "
                f"| {t.get('owner', 'unassigned')} | {issue_s} |"
            )
        lines.append("")

    lines += [
        "---",
        "",
        "Priority is derived from points at risk, not preference. P0 blocks a rubric row worth 3 or",
        "more points or blocks someone else's work; P1 is a smaller row or degraded evidence; P2 is",
        "quality; P3 is optional. A ticket with `rubric: none` is still required by the brief — it",
        "simply carries no row of its own.",
        "",
        f"_{done} of {len(tickets)} tickets complete._",
        "",
    ]
    (TICKETS / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def ensure_labels(dry_run: bool) -> None:
    for name, color, description in LABELS:
        if dry_run:
            print(f"[dry-run] label {name}")
            continue
        run(
            ["gh", "label", "create", name, "--color", color,
             "--description", description, "--force"],
            check=False,
        )


def issue_body(t: dict) -> str:
    meta = [
        f"**Rubric row:** {t.get('rubric', 'none')} · "
        f"**Points at risk:** {t.get('points_at_risk', 0)} · "
        f"**Area:** {t.get('area', '')} · "
        f"**Part:** {PART_DISPLAY.get(part_of(t), '—')}",
        f"**Ticket:** `docs/tickets/{t['_path'].name}`",
    ]
    if t.get("blocked_by"):
        meta.append(f"**Blocked by:** {', '.join(t['blocked_by'])}")
    if t.get("blocks"):
        meta.append(f"**Blocks:** {', '.join(t['blocks'])}")
    body = t["_body"]
    body = re.sub(r"^# .*\n+", "", body)  # the title is the issue title
    return "\n".join(meta) + "\n\n" + body


def create_issues(tickets: list[dict], dry_run: bool) -> dict[str, str]:
    created: dict[str, str] = {}
    for t in tickets:
        if t.get("github"):
            continue
        title = f"{t['id']}: {t['title']}"
        labels = [t.get("priority", "P2"), t.get("type", "task"), t.get("area", "infra")]
        labels += PART_LABELS.get(part_of(t), [])
        if dry_run:
            print(f"[dry-run] issue: {title}  labels={labels}")
            continue
        tmp = TICKETS / f".{t['id']}.body.tmp"
        tmp.write_text(issue_body(t), encoding="utf-8")
        try:
            result = run([
                "gh", "issue", "create",
                "--title", title,
                "--body-file", str(tmp),
                *sum((["--label", lab] for lab in labels), []),
            ])
        finally:
            tmp.unlink(missing_ok=True)
        url = result.stdout.strip().splitlines()[-1]
        created[t["id"]] = url
        t["github"] = url
        print(f"  {t['id']} -> {url}")
    return created


def stamp_github_urls(tickets: list[dict], created: dict[str, str]) -> None:
    """Write the issue URL into each ticket's frontmatter and append a log line."""
    for t in tickets:
        if t["id"] not in created:
            continue
        path: Path = t["_path"]
        text = path.read_text(encoding="utf-8")
        url = created[t["id"]]
        text = text.replace(
            "\nowner:", f"\ngithub: {url}\nowner:", 1
        )
        text = text.rstrip("\n") + f"\n- mirrored to GitHub issue {url}\n"
        path.write_text(text, encoding="utf-8")


def sync_part_labels(tickets: list[dict], dry_run: bool) -> None:
    """Apply the part1/part2 labels to issues that already exist.

    Issues are labelled at creation, so tickets mirrored before the part field existed carry none.
    `gh issue edit --add-label` is idempotent, which keeps this safe to re-run.
    """
    for t in tickets:
        labels = PART_LABELS.get(part_of(t), [])
        if not t.get("github") or not labels:
            continue
        if dry_run:
            print(f"[dry-run] label {t['id']} -> {labels}")
            continue
        run(["gh", "issue", "edit", t["github"],
             *sum((["--add-label", lab] for lab in labels), [])], check=False)


def cross_link(tickets: list[dict], dry_run: bool) -> None:
    """Rewrite A3-NNN dependency references in issue bodies as #N links, now that numbers exist."""
    number = {
        t["id"]: t["github"].rsplit("/", 1)[-1] for t in tickets if t.get("github")
    }
    for t in tickets:
        if not t.get("github"):
            continue
        body = issue_body(t)
        # Negative lookbehind for "/" so the ticket's own filename path is left intact; only
        # dependency references and prose mentions become issue links.
        linked = re.sub(
            r"(?<![/\w-])A3-(\d{3})\b",
            lambda m: f"#{number['A3-' + m.group(1)]}" if ("A3-" + m.group(1)) in number
            else m.group(0),
            body,
        )
        if linked == body:
            continue
        if dry_run:
            print(f"[dry-run] cross-link {t['id']}")
            continue
        tmp = TICKETS / f".{t['id']}.body.tmp"
        tmp.write_text(linked, encoding="utf-8")
        try:
            run(["gh", "issue", "edit", t["github"], "--body-file", str(tmp)], check=False)
        finally:
            tmp.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--github", action="store_true", help="mirror tickets to GitHub issues")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    tickets = load_tickets()
    print(f"loaded {len(tickets)} tickets")

    created: dict[str, str] = {}
    if args.github:
        ensure_labels(args.dry_run)
        created = create_issues(tickets, args.dry_run)
        if created:
            stamp_github_urls(tickets, created)
            tickets = load_tickets()  # reload so the board picks up the new github: fields
        sync_part_labels(tickets, args.dry_run)
        cross_link(tickets, args.dry_run)

    write_index(tickets)
    print(f"wrote {TICKETS / 'INDEX.md'}")
    if created:
        print(json.dumps(created, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
